services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quizine-app
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - ALLOWED_HOSTS=quiz.kerboul.me
    restart: unless-stopped